/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oswalfuentes_lab6;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAMEDA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_cliente = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_edad_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_id_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_nacionalidad_cliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nacimiento_cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_dinero_cliente = new javax.swing.JTextField();
        bt_guardar_cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jd_jefes = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tf_nombre_jefe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_edad_jefe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_id_jefe = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_nacionalidad_jefe = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_nacimiento_jefe = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bt_color_jefe = new javax.swing.JButton();
        bt_guardar_jefe = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_seccion_jefe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jd_empleados = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        tf_nombre_empleado = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_edad_empleado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_id_empleado = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_nacionalidad_empleado = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_nacimiento_empleado = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        bt_color_empleado = new javax.swing.JButton();
        bt_guardar_empleado = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cb_seccion_empleado = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        sp_entrada_empleado = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        sp_salida_empleado = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree3 = new javax.swing.JTree();
        jLabel31 = new javax.swing.JLabel();
        cb_estado_empleado = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        tf_sueldo_empleado = new javax.swing.JTextField();
        jd_familiares = new javax.swing.JDialog();
        jd_baleadas = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        tf_precio_baleada = new javax.swing.JTextField();
        tf_ingrediente_baleada = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bt_agregaringrediente_baleada = new javax.swing.JToggleButton();
        bt_agregar_baleada = new javax.swing.JButton();
        jd_gatos = new javax.swing.JDialog();
        tf_precio_gatos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_peso_gatos = new javax.swing.JTextField();
        tf_altura_gatos = new javax.swing.JTextField();
        bt_agregar_gatos = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jd_cliente.setTitle("Agregar cliente");

        jLabel3.setText("Nombre");

        jLabel4.setText("Edad");

        jLabel5.setText("ID");

        jLabel6.setText("Nacionalidad");

        jLabel7.setText("Lugar de nacimiento");

        jLabel8.setText("Color");

        bt_color.setText("-");
        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        jLabel10.setText("Dinero");

        bt_guardar_cliente.setText("Guardar cliente");
        bt_guardar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar_clienteMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jTree2);

        javax.swing.GroupLayout jd_clienteLayout = new javax.swing.GroupLayout(jd_cliente.getContentPane());
        jd_cliente.getContentPane().setLayout(jd_clienteLayout);
        jd_clienteLayout.setHorizontalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_clienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26))
                            .addGroup(jd_clienteLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)))
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nacionalidad_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(tf_nombre_cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_id_cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_edad_cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_nacimiento_cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dinero_cliente)))
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bt_guardar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_clienteLayout.setVerticalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_edad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nacionalidad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nacimiento_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(bt_color))
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_dinero_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(75, 75, 75)
                .addComponent(bt_guardar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jd_jefes.setTitle("Agregar jefe");

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        jLabel13.setText("ID");

        jLabel14.setText("Nacionalidad");

        jLabel15.setText("Lugar de nacimiento");

        jLabel16.setText("Color");

        bt_color_jefe.setText("-");
        bt_color_jefe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_color_jefeMouseClicked(evt);
            }
        });

        bt_guardar_jefe.setText("Guardar jefe");
        bt_guardar_jefe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar_jefeMouseClicked(evt);
            }
        });

        jLabel19.setText("Seccion de trabajo");

        cb_seccion_jefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta de gatos", "Venta de baleadas" }));

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jd_jefesLayout = new javax.swing.GroupLayout(jd_jefes.getContentPane());
        jd_jefes.getContentPane().setLayout(jd_jefesLayout);
        jd_jefesLayout.setHorizontalGroup(
            jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jefesLayout.createSequentialGroup()
                .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jefesLayout.createSequentialGroup()
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jefesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(26, 26, 26))
                            .addGroup(jd_jefesLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)))
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nacionalidad_jefe, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nombre_jefe, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_id_jefe, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_edad_jefe, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nacimiento_jefe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(bt_color_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_seccion_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_jefesLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(bt_guardar_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jd_jefesLayout.setVerticalGroup(
            jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jefesLayout.createSequentialGroup()
                .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_jefesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_nombre_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tf_edad_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_id_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_nacionalidad_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_nacimiento_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(bt_color_jefe))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jefesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cb_seccion_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(bt_guardar_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_jefesLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jd_empleados.setTitle("Agregar empleado");

        jLabel22.setText("Nombre");

        jLabel23.setText("Edad");

        jLabel24.setText("ID");

        jLabel25.setText("Nacionalidad");

        jLabel26.setText("Lugar de nacimiento");

        jLabel27.setText("Color");

        bt_color_empleado.setText("-");
        bt_color_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_color_empleadoMouseClicked(evt);
            }
        });

        bt_guardar_empleado.setText("Guardar empleado");
        bt_guardar_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar_empleadoMouseClicked(evt);
            }
        });

        jLabel28.setText("Seccion de trabajo");

        cb_seccion_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocina", "Venta de Gatos", "Venta de baleadas" }));

        jLabel29.setText("Hora de entrada");

        jLabel30.setText("Hora de salida");

        jScrollPane3.setViewportView(jTree3);

        jLabel31.setText("Estado");

        cb_estado_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Ocupado" }));

        jLabel32.setText("Sueldo");

        javax.swing.GroupLayout jd_empleadosLayout = new javax.swing.GroupLayout(jd_empleados.getContentPane());
        jd_empleados.getContentPane().setLayout(jd_empleadosLayout);
        jd_empleadosLayout.setHorizontalGroup(
            jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadosLayout.createSequentialGroup()
                .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_empleadosLayout.createSequentialGroup()
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_empleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addGap(26, 26, 26))
                            .addGroup(jd_empleadosLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel32))))
                                .addGap(18, 18, 18)))
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nacionalidad_empleado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_id_empleado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_edad_empleado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_nacimiento_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(bt_color_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_empleadosLayout.createSequentialGroup()
                                .addComponent(sp_entrada_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(sp_salida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_seccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_sueldo_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_estado_empleado, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE))))
                    .addGroup(jd_empleadosLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(bt_guardar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jd_empleadosLayout.setVerticalGroup(
            jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_empleadosLayout.createSequentialGroup()
                .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_empleadosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tf_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tf_edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tf_nacionalidad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tf_nacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(bt_color_empleado))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cb_seccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(sp_entrada_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(sp_salida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(cb_estado_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tf_sueldo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(bt_guardar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_empleadosLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jd_familiares.setTitle("Agregar familiares");

        javax.swing.GroupLayout jd_familiaresLayout = new javax.swing.GroupLayout(jd_familiares.getContentPane());
        jd_familiares.getContentPane().setLayout(jd_familiaresLayout);
        jd_familiaresLayout.setHorizontalGroup(
            jd_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jd_familiaresLayout.setVerticalGroup(
            jd_familiaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jd_baleadas.setTitle("Agregar baleadas");

        jLabel17.setText("Precio");

        jLabel18.setText("Ingrediente");

        bt_agregaringrediente_baleada.setText("Agregar");
        bt_agregaringrediente_baleada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregaringrediente_baleadaActionPerformed(evt);
            }
        });

        bt_agregar_baleada.setText("Agregar baleada");

        javax.swing.GroupLayout jd_baleadasLayout = new javax.swing.GroupLayout(jd_baleadas.getContentPane());
        jd_baleadas.getContentPane().setLayout(jd_baleadasLayout);
        jd_baleadasLayout.setHorizontalGroup(
            jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_baleadasLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_ingrediente_baleada)
                    .addComponent(tf_precio_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_agregaringrediente_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jd_baleadasLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(bt_agregar_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_baleadasLayout.setVerticalGroup(
            jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_baleadasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_precio_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_baleadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ingrediente_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(bt_agregaringrediente_baleada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(bt_agregar_baleada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jd_gatos.setTitle("Agregar gatos");

        jLabel20.setText("Precio");

        jLabel21.setText("Peso");

        jLabel33.setText("Altura");

        bt_agregar_gatos.setText("Agregar gato");
        bt_agregar_gatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_gatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_gatosLayout = new javax.swing.GroupLayout(jd_gatos.getContentPane());
        jd_gatos.getContentPane().setLayout(jd_gatosLayout);
        jd_gatosLayout.setHorizontalGroup(
            jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_gatosLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_agregar_gatos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_gatosLayout.createSequentialGroup()
                        .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_precio_gatos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(tf_peso_gatos)
                            .addComponent(tf_altura_gatos))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jd_gatosLayout.setVerticalGroup(
            jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_gatosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_precio_gatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_peso_gatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_gatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_altura_gatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(bt_agregar_gatos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Cliente");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Jefe");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Empleado");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione el tipo de persona que desea agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );

        jTabbedPane1.addTab("Agregar personas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Agregar familiares");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        jTabbedPane1.addTab("Agregar familiares", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jButton5.setText("Baleadas");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setText("Gatos");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el tipo de articulo que desea agregar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("Agregar articulos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane2.addTab("Agregar", jPanel4);

        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jt_listar);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Cliente");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Empleado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Jefe");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Familiares");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Baleadas");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Gatos");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton6)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Listar", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modificar/Eliminar", jPanel6);

        jMenu1.setText("File");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar como");
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("About");
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Salir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar_clienteMouseClicked
        int ticket, edad, id;
        float dinero;
        String nacionalidad, lugar_nacimiento, nombre;
        Color color;
        ticket = t;
        t++;
        edad = Integer.parseInt(tf_edad_cliente.getText());
        id = Integer.parseInt(tf_id_cliente.getText());
        dinero = Integer.parseInt(tf_dinero_cliente.getText());
        nacionalidad = tf_nacionalidad_cliente.getText();
        lugar_nacimiento = tf_nacimiento_cliente.getText();
        nombre = tf_nombre_cliente.getText();
        color = bt_color.getForeground();
        personas.add(new Clientes(ticket, dinero, edad, id, nacionalidad, lugar_nacimiento, nombre, color));
        JOptionPane.showMessageDialog(null, "Se agregó al cliente exitosamente");
        jd_cliente.dispose();//Cierra la ventana
        tf_edad_cliente.setText("");
        tf_id_cliente.setText("");
        tf_dinero_cliente.setText("");
        tf_nacionalidad_cliente.setText("");
        tf_nacimiento_cliente.setText("");
        tf_nombre_cliente.setText("");
    }//GEN-LAST:event_bt_guardar_clienteMouseClicked

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        Color c;
        c = JColorChooser.showDialog(this, "Seleccione el color", Color.BLACK);
        bt_color.setForeground(c);
    }//GEN-LAST:event_bt_colorMouseClicked

    private void bt_color_jefeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_color_jefeMouseClicked
        Color c;
        c = JColorChooser.showDialog(this, "Seleccione el color", Color.BLACK);
        bt_color_jefe.setForeground(c);
    }//GEN-LAST:event_bt_color_jefeMouseClicked

    private void bt_guardar_jefeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar_jefeMouseClicked
        int edad, id;
        String nacionalidad, lugar_nacimiento, nombre, seccion_trabajo;
        Color color;
        edad = Integer.parseInt(tf_edad_jefe.getText());
        id = Integer.parseInt(tf_id_jefe.getText());
        nacionalidad = tf_nacionalidad_jefe.getText();
        lugar_nacimiento = tf_nacimiento_jefe.getText();
        color = bt_color_jefe.getForeground();
        nombre = tf_nombre_jefe.getText();
        seccion_trabajo = (String) cb_seccion_jefe.getSelectedItem();
        personas.add(new Jefes(seccion_trabajo, edad, id, nacionalidad, lugar_nacimiento, nombre, color));
        JOptionPane.showMessageDialog(null, "Se agregó al jefe exitosamente");
        jd_jefes.dispose();//Cierra la ventana
        tf_edad_jefe.setText("");
        tf_id_jefe.setText("");
        tf_nacionalidad_jefe.setText("");
        tf_nacimiento_jefe.setText("");
        tf_nombre_jefe.setText("");
    }//GEN-LAST:event_bt_guardar_jefeMouseClicked

    private void bt_guardar_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar_empleadoMouseClicked
        int edad, id, hora_entrada, hora_salida, sueldo;
        String nacionalidad, lugar_nacimiento, nombre, seccion_trabajo, estado;
        Color color;
        edad = Integer.parseInt(tf_edad_empleado.getText());
        id = Integer.parseInt(tf_id_empleado.getText());
        hora_entrada = (Integer) sp_entrada_empleado.getValue();
        hora_salida = (Integer) sp_salida_empleado.getValue();
        sueldo = Integer.parseInt(tf_sueldo_empleado.getText());
        nacionalidad = tf_nacionalidad_empleado.getText();
        lugar_nacimiento = tf_nacimiento_empleado.getText();
        nombre = tf_nombre_empleado.getText();
        seccion_trabajo = (String) cb_seccion_empleado.getSelectedItem();
        estado = (String) cb_estado_empleado.getSelectedItem();
        color = bt_color_empleado.getForeground();
        personas.add(new Empleado(seccion_trabajo, estado, hora_entrada, hora_salida,
                sueldo, edad, id, nacionalidad, lugar_nacimiento, nombre, color));
        JOptionPane.showMessageDialog(null, "Se agregó al empleado exitosamente");
        jd_empleados.dispose();//Cierra la ventana
        tf_edad_empleado.setText("");
        tf_id_empleado.setText("");
        sp_entrada_empleado.setValue(0);
        sp_salida_empleado.setValue(0);
        tf_sueldo_empleado.setText("");
        tf_nacionalidad_empleado.setText("");
        tf_nacimiento_empleado.setText("");
        tf_nombre_empleado.setText("");
    }//GEN-LAST:event_bt_guardar_empleadoMouseClicked

    private void bt_color_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_color_empleadoMouseClicked
        Color c;
        c = JColorChooser.showDialog(this, "Seleccione el color", Color.BLACK);
        bt_color_empleado.setForeground(c);
    }//GEN-LAST:event_bt_color_empleadoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_cliente.setModal(true);//Bloquear otras ventanas
        jd_cliente.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_cliente.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_cliente.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_jefes.setModal(true);//Bloquear otras ventanas
        jd_jefes.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_jefes.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_jefes.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jd_empleados.setModal(true);//Bloquear otras ventanas
        jd_empleados.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_empleados.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_empleados.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Edad", "Dinero", "Ticket"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
        for (int i = 0; i < personas.size(); i++) {
            if (personas.get(i) instanceof Clientes) {
                Object[] row = {
                    personas.get(i).getNombre(),
                    personas.get(i).getEdad(),
                    ((Clientes) personas.get(i)).getDinero(),
                    ((Clientes) personas.get(i)).getTicket(),};
                modelo.addRow(row);
            }
            jt_listar.setModel(modelo);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Seccion de Trabajo", "Hora de entrada", "Hora de salida", "Sueldo", "Estado"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
        for (int i = 0; i < personas.size(); i++) {
            if (personas.get(i) instanceof Empleado) {
                Object[] row = {
                    personas.get(i).getNombre(),
                    ((Empleado) personas.get(i)).getSeccion_trabajo(),
                    ((Empleado) personas.get(i)).getHora_entrada(),
                    ((Empleado) personas.get(i)).getHora_salida(),
                    ((Empleado) personas.get(i)).getSueldo(),
                    ((Empleado) personas.get(i)).getEstado(),};
                modelo.addRow(row);
            }
            jt_listar.setModel(modelo);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Seccion de Trabajo", "Clientes atendidos", "Gananacia"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
        for (int i = 0; i < personas.size(); i++) {
            if (personas.get(i) instanceof Jefes) {
                Object[] row = {
                    personas.get(i).getNombre(),
                    ((Jefes) personas.get(i)).getSeccion_trabajo(),
                    ((Jefes) personas.get(i)).getClientes_atendidos(),
                    ((Jefes) personas.get(i)).getGanancia(),};
                modelo.addRow(row);
            }
            jt_listar.setModel(modelo);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void bt_agregaringrediente_baleadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregaringrediente_baleadaActionPerformed

    }//GEN-LAST:event_bt_agregaringrediente_baleadaActionPerformed

    private void bt_agregar_gatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_gatosMouseClicked
        int peso, altura, precio;
        precio = Integer.parseInt(tf_precio_gatos.getText());
        peso = Integer.parseInt(tf_peso_gatos.getText());
        altura = Integer.parseInt(tf_altura_gatos.getText());
        articulos.add(new Gatos(peso, altura, precio));
        JOptionPane.showMessageDialog(null, "Se ha agregado al gato exitosamente");
        jd_gatos.dispose();//Cierra la ventana
        tf_precio_gatos.setText("");
        tf_peso_gatos.setText("");
        tf_altura_gatos.setText("");
    }//GEN-LAST:event_bt_agregar_gatosMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        jd_gatos.setModal(true);//Bloquear otras ventanas
        jd_gatos.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_gatos.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_gatos.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Altura", "Peso", "Precio"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
        for (int i = 0; i < articulos.size(); i++) {
            if (articulos.get(i) instanceof Gatos) {
                Object[] row = {
                    ((Gatos) articulos.get(i)).getAltura(),
                    ((Gatos) articulos.get(i)).getPeso(),
                    articulos.get(i).getPrecio(),};
                modelo.addRow(row);
            }
            jt_listar.setModel(modelo);
        }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar_baleada;
    private javax.swing.JButton bt_agregar_gatos;
    private javax.swing.JToggleButton bt_agregaringrediente_baleada;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_color_empleado;
    private javax.swing.JButton bt_color_jefe;
    private javax.swing.JButton bt_guardar_cliente;
    private javax.swing.JButton bt_guardar_empleado;
    private javax.swing.JButton bt_guardar_jefe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_estado_empleado;
    private javax.swing.JComboBox<String> cb_seccion_empleado;
    private javax.swing.JComboBox<String> cb_seccion_jefe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTree jTree3;
    private javax.swing.JDialog jd_baleadas;
    private javax.swing.JDialog jd_cliente;
    private javax.swing.JDialog jd_empleados;
    private javax.swing.JDialog jd_familiares;
    private javax.swing.JDialog jd_gatos;
    private javax.swing.JDialog jd_jefes;
    private javax.swing.JTable jt_listar;
    private javax.swing.JSpinner sp_entrada_empleado;
    private javax.swing.JSpinner sp_salida_empleado;
    private javax.swing.JTextField tf_altura_gatos;
    private javax.swing.JTextField tf_dinero_cliente;
    private javax.swing.JTextField tf_edad_cliente;
    private javax.swing.JTextField tf_edad_empleado;
    private javax.swing.JTextField tf_edad_jefe;
    private javax.swing.JTextField tf_id_cliente;
    private javax.swing.JTextField tf_id_empleado;
    private javax.swing.JTextField tf_id_jefe;
    private javax.swing.JTextField tf_ingrediente_baleada;
    private javax.swing.JTextField tf_nacimiento_cliente;
    private javax.swing.JTextField tf_nacimiento_empleado;
    private javax.swing.JTextField tf_nacimiento_jefe;
    private javax.swing.JTextField tf_nacionalidad_cliente;
    private javax.swing.JTextField tf_nacionalidad_empleado;
    private javax.swing.JTextField tf_nacionalidad_jefe;
    private javax.swing.JTextField tf_nombre_cliente;
    private javax.swing.JTextField tf_nombre_empleado;
    private javax.swing.JTextField tf_nombre_jefe;
    private javax.swing.JTextField tf_peso_gatos;
    private javax.swing.JTextField tf_precio_baleada;
    private javax.swing.JTextField tf_precio_gatos;
    private javax.swing.JTextField tf_sueldo_empleado;
    // End of variables declaration//GEN-END:variables
    int t = 1;
    ArrayList<Persona> personas = new ArrayList();
    ArrayList<Articulos_en_Venta> articulos = new ArrayList();

}
